# Generated by Django 5.1.6 on 2025-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_testimonial_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
