# Generated by Django 5.1.6 on 2025-03-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categery',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
