# Generated by Django 5.1.6 on 2025-03-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
